<?php

return [
    'search_bar' => [
        'component_type' => 'search_bar',
        'component_name' => '搜索栏',
        'icon' => 'icon-search',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'placeholder' => '搜索商品',
            'style' => 'round',
            'show_scan' => true,
            'show_msg' => false,
            'msg_dot' => false,
        ],
        'props_schema' => [
            'placeholder' => ['type' => 'string', 'max' => 20],
            'style' => ['type' => 'enum', 'values' => ['round', 'square']],
            'show_scan' => ['type' => 'boolean'],
            'show_msg' => ['type' => 'boolean'],
            'msg_dot' => ['type' => 'boolean'],
        ],
        'validate_rules' => [],
    ],
    'swiper' => [
        'component_type' => 'swiper',
        'component_name' => '轮播图',
        'icon' => 'icon-image',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'images' => [],
            'autoplay' => true,
            'interval' => 3000,
            'circular' => true,
            'indicator_dots' => true,
        ],
        'props_schema' => [
            'images' => ['type' => 'array', 'max_items' => 10, 'item_fields' => ['url' => 'string', 'link' => 'string']],
            'autoplay' => ['type' => 'boolean'],
            'interval' => ['type' => 'integer', 'min' => 1000, 'max' => 10000],
            'circular' => ['type' => 'boolean'],
            'indicator_dots' => ['type' => 'boolean'],
        ],
        'validate_rules' => [
            'publish' => ['images.min' => 1],
        ],
    ],
    'notice_bar' => [
        'component_type' => 'notice_bar',
        'component_name' => '公告栏',
        'icon' => 'icon-notification',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'content' => '',
            'scrollable' => true,
            'icon' => 'volume',
            'text_color' => '#FF6B35',
            'background_color' => '#FFF7E6',
        ],
        'props_schema' => [
            'content' => ['type' => 'string', 'max' => 200],
            'scrollable' => ['type' => 'boolean'],
            'icon' => ['type' => 'string'],
            'text_color' => ['type' => 'hex_color'],
            'background_color' => ['type' => 'hex_color'],
        ],
        'validate_rules' => [
            'publish' => ['content.required' => true],
        ],
    ],
    'rich_text' => [
        'component_type' => 'rich_text',
        'component_name' => '富文本',
        'icon' => 'icon-edit',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'content' => '',
        ],
        'props_schema' => [
            'content' => ['type' => 'html'],
        ],
        'validate_rules' => [],
    ],
    'image_ad' => [
        'component_type' => 'image_ad',
        'component_name' => '图片广告',
        'icon' => 'icon-image',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'layout' => 'single',
            'images' => [],
        ],
        'props_schema' => [
            'layout' => ['type' => 'enum', 'values' => ['single', 'two_col', 'three_col', 'four_col', 'left1_right2', 'left2_right1']],
            'images' => ['type' => 'array', 'max_items' => 4, 'item_fields' => ['url' => 'string', 'link' => 'string']],
        ],
        'validate_rules' => [
            'publish' => ['images.min' => 1],
        ],
    ],
    'grid_nav' => [
        'component_type' => 'grid_nav',
        'component_name' => '宫格导航',
        'icon' => 'icon-apps',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'columns' => 4,
            'items' => [],
        ],
        'props_schema' => [
            'columns' => ['type' => 'enum', 'values' => [4, 5]],
            'items' => ['type' => 'array', 'max_items' => 10, 'item_fields' => ['icon' => 'string', 'icon_name' => 'string', 'text' => 'string', 'link' => 'string', 'badge' => 'string']],
        ],
        'validate_rules' => [
            'publish' => ['items.min' => 1],
        ],
    ],
    'product_list' => [
        'component_type' => 'product_list',
        'component_name' => '商品列表',
        'icon' => 'icon-list',
        'category' => 'commerce',
        'edition' => 'community',
        'default_props' => [
            'source_type' => 'manual',
            'item_ids' => [],
            'category_id' => '',
            'tag_id' => '',
            'display_count' => 6,
            'sort_by' => 'newest',
            'display_style' => 'two_small',
            'show_sales' => true,
            'show_tags' => false,
            'show_cart' => true,
            'title' => '',
            'icon' => '',
            'tag_text' => '',
            'show_more' => true,
            'more_link' => '',
            'columns' => 2,
        ],
        'props_schema' => [
            'source_type' => ['type' => 'enum', 'values' => ['manual', 'category', 'tag']],
            'item_ids' => ['type' => 'array', 'max_items' => 20],
            'category_id' => ['type' => 'string'],
            'tag_id' => ['type' => 'string'],
            'display_count' => ['type' => 'integer', 'min' => 1, 'max' => 20],
            'sort_by' => ['type' => 'enum', 'values' => ['newest', 'price', 'sales']],
            'display_style' => ['type' => 'enum', 'values' => ['single_large', 'two_small', 'horizontal_scroll', 'list']],
            'show_sales' => ['type' => 'boolean'],
            'show_tags' => ['type' => 'boolean'],
            'show_cart' => ['type' => 'boolean'],
            'title' => ['type' => 'string', 'max' => 20],
            'icon' => ['type' => 'string', 'max' => 30],
            'tag_text' => ['type' => 'string', 'max' => 10],
            'show_more' => ['type' => 'boolean'],
            'more_link' => ['type' => 'string', 'max' => 255],
            'columns' => ['type' => 'integer', 'min' => 1, 'max' => 4],
        ],
        'validate_rules' => [],
    ],
    'coupon' => [
        'component_type' => 'coupon',
        'component_name' => '优惠券',
        'icon' => 'icon-gift',
        'category' => 'commerce',
        'edition' => 'community',
        'default_props' => [
            'coupon_ids' => [],
        ],
        'props_schema' => [
            'coupon_ids' => ['type' => 'array', 'max_items' => 10],
        ],
        'validate_rules' => [
            'publish' => ['coupon_ids.min' => 1],
        ],
    ],
    'seckill' => [
        'component_type' => 'seckill',
        'component_name' => '限时秒杀',
        'icon' => 'icon-thunder',
        'category' => 'marketing',
        'edition' => 'community',
        'default_props' => [
            'session_id' => '',
            'max_items' => 4,
        ],
        'props_schema' => [
            'session_id' => ['type' => 'string'],
            'max_items' => ['type' => 'integer', 'min' => 1, 'max' => 6],
        ],
        'validate_rules' => [
            'publish' => ['session_id.required' => true],
        ],
    ],
    'group_buy' => [
        'component_type' => 'group_buy',
        'component_name' => '拼团活动',
        'icon' => 'icon-user-group',
        'category' => 'marketing',
        'edition' => 'community',
        'default_props' => [
            'group_buy_ids' => [],
            'display_style' => 'grid',
        ],
        'props_schema' => [
            'group_buy_ids' => ['type' => 'array', 'max_items' => 6],
            'display_style' => ['type' => 'enum', 'values' => ['grid', 'horizontal_scroll']],
        ],
        'validate_rules' => [
            'publish' => ['group_buy_ids.min' => 1],
        ],
    ],
    'coupon_receive' => [
        'component_type' => 'coupon_receive',
        'component_name' => '优惠券领取',
        'icon' => 'icon-send',
        'category' => 'marketing',
        'edition' => 'community',
        'default_props' => [
            'coupon_ids' => [],
        ],
        'props_schema' => [
            'coupon_ids' => ['type' => 'array', 'max_items' => 6],
        ],
        'validate_rules' => [
            'publish' => ['coupon_ids.min' => 1],
        ],
    ],
    'point_exchange' => [
        'component_type' => 'point_exchange',
        'component_name' => '积分兑换',
        'icon' => 'icon-star',
        'category' => 'marketing',
        'edition' => 'open_source',
        'default_props' => [
            'point_item_ids' => [],
        ],
        'props_schema' => [
            'point_item_ids' => ['type' => 'array', 'max_items' => 6],
        ],
        'validate_rules' => [
            'publish' => ['point_item_ids.min' => 1],
        ],
    ],
    'promo_banner' => [
        'component_type' => 'promo_banner',
        'component_name' => '推广横幅',
        'icon' => 'icon-bug',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'style' => 'solid',
            'bg_color1' => '#2563eb',
            'bg_color2' => '#3b82f6',
            'icon' => '',
            'icon_bg' => '',
            'title' => '',
            'subtitle' => '',
            'btn_text' => '',
            'btn_link' => '',
            'show_pulse' => false,
        ],
        'props_schema' => [
            'style' => ['type' => 'enum', 'values' => ['solid', 'glass', 'dark']],
            'bg_color1' => ['type' => 'hex_color'],
            'bg_color2' => ['type' => 'hex_color'],
            'icon' => ['type' => 'string', 'max' => 30],
            'icon_bg' => ['type' => 'hex_color'],
            'title' => ['type' => 'string', 'max' => 50],
            'subtitle' => ['type' => 'string', 'max' => 100],
            'btn_text' => ['type' => 'string', 'max' => 20],
            'btn_link' => ['type' => 'string', 'max' => 255],
            'show_pulse' => ['type' => 'boolean'],
        ],
        'validate_rules' => [
            'publish' => ['title.required' => true],
        ],
    ],
    'promo_grid' => [
        'component_type' => 'promo_grid',
        'component_name' => '推广卡片网格',
        'icon' => 'icon-mind-mapping',
        'category' => 'basic',
        'edition' => 'community',
        'default_props' => [
            'layout' => 'one_big_two_small',
            'cards' => [],
        ],
        'props_schema' => [
            'layout' => ['type' => 'enum', 'values' => ['one_big_two_small', 'two_col', 'three_col']],
            'cards' => ['type' => 'array', 'max_items' => 4, 'item_fields' => ['title' => 'string', 'subtitle' => 'string', 'bg_color1' => 'string', 'bg_color2' => 'string', 'text_color' => 'string', 'icon' => 'string', 'btn_text' => 'string', 'link' => 'string']],
        ],
        'validate_rules' => [
            'publish' => ['cards.min' => 1],
        ],
    ],
    'brand_zone' => [
        'component_type' => 'brand_zone',
        'component_name' => '品牌专区',
        'icon' => 'icon-trophy',
        'category' => 'commerce',
        'edition' => 'community',
        'default_props' => [
            'title' => '品牌专区',
            'more_text' => '查看全部',
            'more_link' => '',
            'columns' => 4,
            'source_type' => 'system',
            'is_hot' => 0,
            'limit' => 8,
            'items' => [],
        ],
        'props_schema' => [
            'title' => ['type' => 'string', 'max' => 20],
            'more_text' => ['type' => 'string', 'max' => 10],
            'more_link' => ['type' => 'string', 'max' => 255],
            'columns' => ['type' => 'integer', 'min' => 3, 'max' => 6],
            'source_type' => ['type' => 'enum', 'values' => ['system', 'custom']],
            'is_hot' => ['type' => 'integer', 'min' => 0, 'max' => 1],
            'limit' => ['type' => 'integer', 'min' => 1, 'max' => 20],
            'items' => ['type' => 'array', 'max_items' => 12, 'item_fields' => ['name' => 'string', 'logo' => 'string', 'link' => 'string']],
        ],
        'validate_rules' => [
            // system 模式不需要 items，custom 模式前端校验
        ],
    ],
];